# Generated by Django 6.0.1 on 2026-04-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('etapa', models.CharField(choices=[('PRO', 'Prospección'), ('PRP', 'Propuesta'), ('NEG', 'Negociación'), ('GAN', 'Cerrada Ganada'), ('PER', 'Cerrada Perdida')], default='PRO', max_length=3)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='core.cliente')),
            ],
        ),
    ]
